---
title: 'Agricultural projects: Project Appraisal Documents Descriptives'
author: "Luiza Andrade"
date: "4/22/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, include = FALSE}
library(tidyverse)
library(expss)
library(eulerr)
library(RColorBrewer)
 path_dt <- file.path("C:/Users/wb501238/WBG/Maria Ruth Jones - DIME Analytics/Operations portal scraping/data")

  projects_value <- readRDS(file.path(path_dt, "ag-projects-value-summary.RDS"))
  projects_region <- readRDS(file.path(path_dt, "ag-projects-region-summary.RDS"))
  yearly <- readRDS(file.path(path_dt,"ag-projects-year-summary.RDS"))
  project_long <- readRDS(file.path(path_dt,"ag-projects-summary.RDS"))
  projects <- 
      readRDS(file.path(path_dt, 
                        "ag-projects-constructed.RDS"))
  
  components <- c("demo", "ext", "contact", "ffs")
  themes <- c("gender", "com", "climate")
  
  
  line_graph <-
    function(x) {
      use_labels(x,
                 ggplot(data = x,
                        aes(x = year,
                            y  = pct,
                            color = expression)) + 
                   geom_line(size = 1) + 
                   geom_point(shape = 21,
                              size = 2,
                              fill = "white") + 
                   scale_color_brewer(palette = "Dark2") +
                   scale_x_continuous(breaks = seq(1990, 2020, by = 5),
                                      minor_breaks = seq(1990, 2020, by = 1)) +
                   theme(legend.position = "top")
      )
    }

```

# Notes on the data

We scraped the operations portal and 

```{r}

  all <- 
    project_long %>%
    filter(year != 0) %>%
    pivot_longer(cols = c(pads, projects),
                 names_to = "what",
                 values_to = "count")
  use_labels(project_long[project_long$year != 0,],
  ggplot(data = project_long[project_long$year != 0,],
         aes(x = year)) +
        geom_bar(aes(y = projects),
                 stat = "identity",
                 color = brewer.pal(3, "Dark2")[1],
                 fill = brewer.pal(3, "Dark2")[1]) +
        geom_bar(aes(y = pads),
                 stat = "identity",
                 color = brewer.pal(3, "Dark2")[2],
                 fill = brewer.pal(3, "Dark2")[2]) +
        scale_color_brewer(palette = "Dark2") +
        scale_fill_brewer(palette = "Dark2") +
        theme(legend.position = "bottom",
              axis.ticks.x = element_blank())
  )

````


# Descriptives

```{r}

  regions <- 
    projects_region %>%
    filter(expression != "FAO")

  use_labels(regions,
      ggplot(data = regions,
             aes(x = expression,
                 y = pct,
                 color = expression,
                 fill = expression)) +
        geom_bar(stat = "identity") +
        scale_color_brewer(palette = "Dark2") +
        scale_fill_brewer(palette = "Dark2") +
        facet_wrap(~ region) +
        theme(legend.position = "bottom",
              axis.ticks.x = element_blank(),
              axis.text.x=element_blank())
    )
```

```{r}

  value <- 
    projects_value %>%
    filter(expression != "FAO")

  use_labels(value,
      ggplot(data = value,
             aes(x = expression,
                 y = median,
                 color = expression,
                 fill = expression)) +
        geom_bar(stat = "identity") +
        scale_color_brewer(palette = "Dark2") +
        scale_fill_brewer(palette = "Dark2") +
        ggtitle("Median net commitment") +
        theme(legend.position = "bottom",
              axis.ticks.x = element_blank(),
              axis.text.x=element_blank())
    )
  
   use_labels(value,
      ggplot(data = value,
             aes(x = expression,
                 y = total,
                 color = expression,
                 fill = expression)) +
        geom_bar(stat = "identity") +
        scale_color_brewer(palette = "Dark2") +
        scale_fill_brewer(palette = "Dark2") +
        ggtitle("Total net commitment") +
        theme(legend.position = "bottom",
              axis.ticks.x = element_blank(),
              axis.text.x=element_blank())
    )
```

```{r}
  cross_cutting <-
    yearly %>%
    filter(expression %in% c("Gender", "Commercialization", "Climate"))

    line_graph(cross_cutting)
  
```

```{r}
  ext <-
    yearly %>%
    filter(expression %in% c("Agricultural extension", "Demonstration plot", "Contact farmer"))

    line_graph(ext)
  
```

```{r}
   fao <-
    yearly %>%
    filter(expression %in% c("Farmer field school", "FAO"))
    
  line_graph(fao)
```

# Are farmer field schools projects always implemented in partnetship with FAO? 
```{r}

  fao_projects <-
    projects %>%
    filter(fao == TRUE) %>%
    select(id) %>%
    unlist %>%
    unname

  ffs_projects <-
      projects %>%
      filter(ffs == TRUE) %>%
      select(id) %>%
      unlist %>%
      unname
  
   fao_projects <-
    projects %>%
    filter(fao == TRUE) %>%
    select(id) %>%
    unlist %>%
    unname
  
  ffs_projects <-
    projects %>%
    filter(ffs == TRUE) %>%
    select(id) %>%
    unlist %>%
    unname
  
  euler <- list(`Farmer field school` = ffs_projects,
                `FAO` = fao_projects)
  
  colors <- brewer.pal(3, "Dark2")
  
  plot(euler(euler),
       fills = list(fill = colors, 
                    alpha = .5),
       edges = FALSE,
       quantities = list(fontefamily = "mono"),
       counts = TRUE)
  
```